### ISSUE TITLE
关于sa_layers

### ISSUE THREAD

**Issue by 3AllenIverson** [wofmanaf/SA-Net#1]
作者您好，我看在sa_resnet代码时第一个block卷积完的通道数为64，按64通道分一组，
sa_layers中该句x_0, x_1 = x.chunk(2, dim=1)就分不了两组了

**Comment by wofmanaf** [comment]
对于BasicBlock,第一个block卷积完的通道数为64，此时sa_layers会报错，对于Bottleneck，第一个block卷积完的通道数为256，此时代码能够正常运行。论文没有涉及18和34层的网络结构，所以这点忽视了。现在已更正

**Comment by LCCmango** [comment]
您好，很棒的工作，关于FIG.4 ，我想请教一下是怎么得到最后一个阶段的top1.acc然后按分组画出来的，如果可以的话麻烦您告知一下大致的步骤
