### ISSUE TITLE
spatial attention的疑问

### ISSUE THREAD

**Issue by XinYu-Andy** [wofmanaf/SA-Net#8]
作者你好，我看了文章以及代码后对提到的spatial attention有两个疑问：
1.得到的attention map似乎不仅仅是1*H*W维的，而是仍然有通道维，即C*H*W?似乎不是纯粹的spatial attention。
2. 文章提到在得到spatial map的第一步是用的GN，但事实上，如果设置nn.GroupNorm(channel // (2 * groups), channel // (2 * groups)),是否就等价于InstanceNorm了，这一步和Group没什么关系。

谢谢！

**Comment by XinYu-Andy** [comment]
你好，打扰了，刚刚又遇到另一个疑问：
3. 既然GN那一步已经学了一个scale和shift，为何还要在学一个W2,b2?似乎重复了？

**Comment by wofmanaf** [comment]
第一个问题，我的理解是虽然有通道维度，但是不同通道间的特征没有进行交互，应该算是spatial attention。第二个问题，这里使用的GN是等价于InstanceNorm,实际上InstanceNorm应该算是GroupNorm的特例。第三个问题，在消融实验中去掉W2,b2，Top-1准确率只降低了0.12，似乎有些重复，但是换成1x1的卷积效果也一样。经过后来的思考，应该是开始的时候的通道分割有问题，如果开始时采用两个1x1的卷积使通道维度各降维原来的1/2,在分别进行channel attention和spatial attention可能要好一些（没有做实验验证），但这么做会增加一些参数量，违背了文章的初衷
